sidebar.classes=Класы

home.sidebar=Галоўная
home.title=Вікіпедыя Hjson++
home.description=Гэта вікіпедыя, пасвечанная біблятэке Hjson++.

table.field=Поле
table.type=Тып
table.notes=Апісанне

field.goida=ГОЙДААА
field.meow=Мяў:3